export type Language = 'ko' | 'en' | 'ja' | 'zh' | 'es' | 'fr';

export const healthTips = [
  { 
    id: '1',
    title: "🎧 소음성 난청 예방 5계명", 
    desc: "당신의 소중한 청력을 지키는 가장 확실한 방법, 60-60 법칙을 기억하세요.", 
    content: `
### 1. 60-60 법칙 준수
이어폰 사용 시 최대 볼륨의 **60% 이하**로 설정하고, **60분 사용 후에는 반드시 10분 이상** 휴식을 취하세요.

### 2. 소음 노출 최소화
공사장이나 클럽 등 큰 소음이 발생하는 장소는 가급적 피하고, 불가피한 경우 **귀마개를 착용**하세요.

### 3. 정기적인 청력 검사
1년에 한 번은 전문가를 통해 청력 상태를 점검하는 것이 좋습니다. **조기 발견이 가장 중요합니다.**

### 4. 귀 건강에 좋은 음식 섭취
아연과 마그네슘이 풍부한 견과류, 해조류 등을 꾸준히 섭취하여 청각 세포를 보호하세요.

### 5. 충분한 휴식과 스트레스 관리
과도한 피로는 청각 신경에 무리를 줄 수 있습니다. 규칙적인 생활 습관과 충분한 수면을 유지하세요.
    `,
    tag: "예방 가이드",
    img: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800"
  },
  { 
    id: '2',
    title: "🥦 귀 건강을 위한 슈퍼푸드", 
    desc: "아연, 마그네슘, 엽산이 풍부한 음식을 섭취하면 청력 감퇴 예방에 큰 도움이 됩니다.", 
    content: `
### 청력을 지키는 3대 필수 영양소

**1. 아연 (Zinc)**
청각 신경의 노화를 방지하고 이명 완화에 도움을 줍니다. 
- *추천 식품: 굴, 소고기, 계란 노른자*

**2. 마그네슘 (Magnesium)**
소음으로부터 내이의 유모세포를 보호하는 역할을 합니다. 
- *추천 식품: 아몬드, 바나나, 시금치*

**3. 엽산 (Folic Acid)**
혈액 순환을 도와 청각 기관으로의 영양 공급을 원활하게 합니다. 
- *추천 식품: 브로콜리, 아스파라거스, 오렌지*
    `,
    tag: "식이 요법",
    img: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=800"
  },
  { 
    id: '3',
    title: "🌿 이명 완화를 위한 생활 습관", 
    desc: "스트레스 관리와 충분한 휴식, 그리고 백색소음을 활용한 이명 케어 방법을 알아보세요.", 
    content: `
### 이명과 작별하는 4가지 방법

이명은 외부 소리 자극 없이 귀에서 소리가 들리는 현상입니다. 생활 습관 개선으로 충분히 완화할 수 있습니다.

1. **조용한 환경 피하기**
너무 조용한 곳에서는 이명이 더 크게 느껴질 수 있습니다. 잔잔한 배경음악이나 백색소음을 활용하세요.

2. **카페인과 알코올 제한**
중추신경계를 자극하여 이명을 악화시킬 수 있으므로 섭취를 줄이는 것이 좋습니다.

3. **규칙적인 운동**
혈액순환을 개선하여 귀 건강에 긍정적인 영향을 줍니다.

4. **숙면 취하기**
피로는 이명의 가장 큰 적입니다. 일정한 수면 패턴을 유지하세요.
    `,
    tag: "이명 케어",
    img: "https://images.unsplash.com/photo-1516062423079-7ca13cdc7f5a?q=80&w=800"
  },
  { 
    id: '4',
    title: "🦻 보청기 선택 시 필수 체크리스트", 
    desc: "나의 청력 상태와 생활 환경에 맞는 최적의 보청기를 고르는 방법을 확인하세요.", 
    content: `
### 나에게 딱 맞는 보청기 찾기

보청기는 개인의 청력 특성에 맞춘 정밀 의료기기입니다.

1. **정확한 청력 검사**
이비인후과 전문의를 통해 정확한 청력 손실 정도를 파악하는 것이 첫 번째 단계입니다.

2. **착용 목적과 환경 고려**
주로 대화를 많이 하는지, 야외 활동이 많은지 등 본인의 생활 패턴을 고려하여 기능을 선택하세요.

3. **형태 선택 (귓속형 vs 귀걸이형)**
외관상 노출 정도와 착용 편의성에 따라 본인에게 맞는 형태를 선택합니다.

4. **사후 관리 서비스 확인**
보청기는 지속적인 피팅이 필요하므로 A/S가 용이한 전문 센터를 선택하세요.
    `,
    tag: "기기 가이드",
    img: "https://images.unsplash.com/photo-1590602846989-e99596d2a6ee?q=80&w=800"
  }
];

export const translations = {
  en: {
    welcome: "Hey! Welcome to Obige Smart Hearing Agent! 👋",
    intro: "I'm here to help you assess your hearing health using AI. We've helped thousands of people understand their hearing better. 😊",
    choose: "Choose from below...",
    startTest: "Hearing Test",
    hearingAid: "Hearing Aid Info",
    others: "Others",
    askAge: "First, what is your age?",
    askGender: "What is your gender?",
    male: "Male",
    female: "Female",
    askNoise: "Do you have frequent noise exposure?",
    askTinnitus: "Do you experience tinnitus (ringing in ears)?",
    askExisting: "Any existing hearing issues?",
    yes: "Yes",
    no: "No",
    ptaIntro: "Great! Now we'll start the Pure Tone Test. Please wear headphones in a quiet place. 🎧",
    ptaStart: "I'm ready, start test",
    ptaTesting: "Testing {freq} Hz...",
    ptaHeard: "I Heard It",
    ptaNotHeard: "No Sound",
    calculating: "Analyzing your results with AI... 🧠",
    resultsTitle: "Your Hearing Test Results",
    riskScore: "Risk Score",
    grade: "Grade",
    recommendation: "AI Recommendation",
    retest: "Retest",
    share: "Share Results",
    langSwitch: "Language",
    appName: "OBLIGE",
    logout: "Logout",
    navWelfare: "Find Welfare Funds",
    navHearing: "Hearing Test",
    navGame: "Hearing Game",
    navCommunity: "Hearing Health",
    findMyWelfareBtn: "Find my hidden welfare funds",
    welfarePolicy: "Welfare Policy Recommendations",
    insuranceRecommend: "Insurance Recommendations",
    financeRecommend: "Financial Product Recommendations",
    askAgeGroup: "Please select your age group.",
    youth: "Youth (0~19)",
    adult: "Adult (20~60)",
    senior: "Senior (61~100)",
    startQuestionnaire: "Start Questionnaire",
    questionnaireTitle: "Hearing Self-Assessment",
    next: "Next",
    skipQuestionnaire: "Skip and Start Hearing Test",
    startQuestionnaireBtn: "Start Questionnaire",
    landingTitle: "How old is your hearing?",
    landingSub: "Use our free hearing test!",
    landingBtn: "Start Test",
    nameLabel: "Name",
    namePlaceholder: "Enter your name",
    ageLabel: "Age",
    agePlaceholder: "Enter your age",
    phoneLabel: "Phone Number",
    emailLabel: "Email Address",
    nextStep: "Next Step",
    checkVolume: "Check Volume (1000Hz)",
    communityTitle: "Hearing Health Knowledge",
    communitySub: "Expert tips and latest info on ear health",
    backToList: "Back to List",
    like: "Like",
    shareBtn: "Share",
    comment: "Comment",
    commentPlaceholder: "Leave your thoughts...",
    register: "Register",
    firstComment: "Be the first to comment!",
    frequency: "Frequency",
    progress: "Progress",
    aiReport: "AI Hearing Screening Report",
    hearingAgeScreening: "Hearing Age Screening",
    hearingAgeResult: "Your hearing is at the level of {age} years old",
    keshhTitle: "Korean Evaluation of Subjective Hearing Handicap (KESHH)",
    keshhScore: "KESHH Score",
    keshhCategory: "KESHH Category",
    veryHigh: "Very High",
    points: "Points",
    category: "Category",
    cautionTitle: "CAUTION",
    cautionText: "This test is for screening purposes and is not a medical diagnosis. Please consult a doctor for a detailed hearing examination and accurate diagnosis.",
    shareWithFriends: "Share results with friends",
    always: "Always",
    sometimes: "Sometimes",
    analyzeReport: "Analyze Report",
    analyzingReport: "AI is analyzing your report...",
    reportReady: "Detailed report is ready!",
    downloadPdf: "Download PDF Report",
    detailedAnalysis: "Detailed Hearing Health Analysis",
    preventativeMeasures: "Preventative Measures",
    analysisText: "Based on your results, we recommend regular check-ups and noise protection. Maintaining a healthy lifestyle and avoiding loud environments can help preserve your hearing.",
    grade_Normal: "Normal Hearing",
    grade_Mild: "Mild Hearing Loss",
    grade_Moderate: "Moderate Hearing Loss",
    grade_Severe: "Severe Hearing Loss",
    grade_Profound: "Profound Hearing Loss",
    realTimeConsultationPreparing: "Real-time hearing specialist consultation is under preparation.",
    lineToConnect: "Connect via LINE",
    kakaoTalkToConnect: "Connect via KakaoTalk Channel",
    aboutTitle: "About OBLIGE",
    aboutSub: "Smart Jewelry - A new standard for early diagnosis and treatment of hearing loss",
    aboutDescription: "OBLIGE innovates the hearing loss management market by combining AI, IoT, and medical data. Meet our customized hearing aids, AI-based chatbots, and auditory rehabilitation solutions.",
    aboutSection1Title: "AI-based Customized Early Diagnosis & Rehabilitation Counseling",
    aboutSection1Desc: "We provide data-driven hearing diagnosis and optimized rehabilitation programs through customized hearing loss management solutions using sLLM.",
    aboutFeature1: "AI-based Personalized Diagnosis",
    aboutFeature1Desc: "Hearing status analysis and customized rehabilitation using sLLM",
    aboutFeature2: "Digital Self-Diagnosis System",
    aboutFeature2Desc: "Hearing management without hospital visits",
    aboutFeature3: "Amplifier Link & Accessory Development",
    aboutFeature3Desc: "Enhancing functionality and aesthetics with IoT-linked jewelry",
    aboutFeature4: "Sound Therapy & Art Diary Rehab",
    aboutFeature4Desc: "Integrated cognitive rehab and psychological stability care",
    aboutStatsTitle: "Over 1.5 billion people worldwide and 8.5 million in Korea suffer from hearing impairment.",
    aboutStatsDesc: "The existing hearing aid market has low adoption due to price, accessibility, and convenience issues. OBLIGE solves these problems to improve the quality of life for hearing loss patients.",
    aboutStep1: "Hearing Aid Recommendation after Diagnosis",
    aboutStep2: "Customized Care using Patient Data",
    aboutStep3: "Solution Provision & Feedback Analysis",
    aboutStep4: "Improving Quality of Life & Psychological Well-being",
    contactTitle: "Contact",
    contactSub: "Leave an inquiry and we will contact you within 1-2 business days.",
    contactName: "Name",
    contactPhone: "Phone",
    contactEmail: "Email",
    contactMessage: "Inquiry Content",
    contactAgreement: "Agreement to Collection and Use of Personal Information",
    contactSubmit: "Submit",
    contactSuccess: "Your inquiry has been successfully received. We will contact you soon.",
    contactAgreeCheckbox: "I agree to the collection and use of personal information.",
    preparingTitle: "Service in Preparation",
    preparingSub: "We are preparing for a better service. Please wait a moment.",
    backToHome: "Back to Home",
    saveAsPdf: "Save as PDF",
    print: "Print",
    close: "Close",
  },
  ko: {
    welcome: "안녕하세요! Obige 스마트 청각 에이전트에 오신 것을 환영합니다! 👋",
    intro: "AI를 통해 당신의 청력 건강을 분석해 드릴게요. 이미 수많은 분들이 저희 서비스를 통해 청력을 관리하고 계십니다. 😊",
    choose: "아래 메뉴에서 선택해주세요...",
    startTest: "청력 검사 시작",
    hearingAid: "보청기 정보",
    others: "기타 문의",
    askAge: "먼저, 연령대를 알려주세요.",
    askGender: "성별이 어떻게 되시나요?",
    male: "남성",
    female: "여성",
    askNoise: "소음에 자주 노출되는 환경인가요?",
    askTinnitus: "이명(귀울림) 현상이 있나요?",
    askExisting: "기존에 청력 문제가 있었나요?",
    yes: "네",
    no: "아니오",
    ptaIntro: "좋습니다! 이제 순음 청력 검사를 시작합니다. 조용한 곳에서 이어폰을 착용해 주세요. 🎧",
    ptaStart: "준비됐어요, 시작하기",
    ptaTesting: "{freq} Hz 테스트 중...",
    ptaHeard: "들려요",
    ptaNotHeard: "안 들려요",
    calculating: "AI가 결과를 분석 중입니다... 🧠",
    resultsTitle: "청력 검사 결과 리포트",
    riskScore: "위험도 점수",
    grade: "청력 등급",
    recommendation: "AI 맞춤 권고",
    retest: "다시 검사하기",
    share: "결과 공유하기",
    langSwitch: "언어 선택",
    appName: "오블리주",
    logout: "로그아웃",
    navWelfare: "복지금찾기",
    navHearing: "청력검사",
    navGame: "청력게임",
    navCommunity: "청력건강상식",
    findMyWelfareBtn: "나의 숨은 복지금 찾기",
    welfarePolicy: "복지정책추천",
    insuranceRecommend: "보험추천",
    financeRecommend: "금융상품추천",
    askAgeGroup: "연령대를 선택해주세요.",
    youth: "청소년 (0~19)",
    adult: "청년 (20~60)",
    senior: "노인 (61~100)",
    startQuestionnaire: "문항검사 시작하기",
    questionnaireTitle: "청력 자가진단 문항검사",
    next: "다음",
    skipQuestionnaire: "건너뛰고 바로 청력검사 하기",
    startQuestionnaireBtn: "문항검사 시작하기",
    landingTitle: "나의 청각나이는?",
    landingSub: "무료 청력검사를 활용하세요!",
    landingBtn: "검사 시작하기",
    nameLabel: "이름",
    namePlaceholder: "이름을 입력하세요",
    ageLabel: "나이",
    agePlaceholder: "나이를 입력하세요",
    phoneLabel: "전화번호",
    emailLabel: "이메일 주소",
    nextStep: "다음 단계로",
    checkVolume: "소리 크기 확인하기 (1000Hz)",
    communityTitle: "청력 건강 상식",
    communitySub: "전문가가 알려주는 귀 건강 관리 꿀팁과 최신 정보",
    backToList: "목록으로 돌아가기",
    like: "좋아요",
    shareBtn: "공유하기",
    comment: "댓글",
    commentPlaceholder: "의견을 남겨주세요...",
    register: "등록하기",
    firstComment: "첫 번째 댓글을 남겨보세요!",
    frequency: "주파수",
    progress: "진행률",
    aiReport: "AI 청력스크리닝 리포트",
    hearingAgeScreening: "청력 나이 스크리닝",
    hearingAgeResult: "당신의 청력은 {age}세 수준입니다",
    keshhTitle: "한국형 청각장애평가지수 (KESHH)",
    keshhScore: "KESHH 점수",
    keshhCategory: "KESHH 범주",
    veryHigh: "매우 높음",
    points: "점",
    category: "범주",
    cautionTitle: "주의사항",
    cautionText: "본 검사는 청력 스크리닝 목적으로 제공되며, 의학적 진단을 대신할 수 없습니다. 더 자세한 청력 검진과 정확한 진단은 반드시 의사와 상의하시기 바랍니다.",
    shareWithFriends: "친구와 결과 공유하기",
    always: "항상",
    sometimes: "가끔",
    analyzeReport: "AI 리포트 상세 분석",
    analyzingReport: "AI가 리포트를 상세 분석 중입니다...",
    reportReady: "상세 분석 리포트가 준비되었습니다!",
    downloadPdf: "PDF 리포트 다운로드",
    detailedAnalysis: "청력 건강 상세 분석",
    preventativeMeasures: "청력 보호를 위한 예방법",
    analysisText: "현재 청력 상태를 바탕으로 정기적인 검진과 소음 노출 최소화를 권장합니다. 건강한 생활 습관과 큰 소음이 발생하는 환경을 피하는 것이 청력 보존에 큰 도움이 됩니다.",
    grade_Normal: "정상 청력 (매우 좋음)",
    grade_Mild: "경도 난청 (주의 필요)",
    grade_Moderate: "중도 난청 (보청기 권장)",
    grade_Severe: "고도 난청 (전문가 상담 필수)",
    grade_Profound: "심도 난청 (즉각적인 조치 필요)",
    realTimeConsultationPreparing: "실시간 청력상담사 기능이 준비 중입니다.",
    lineToConnect: "라인으로 연결",
    kakaoTalkToConnect: "카카오톡 채널로 연결",
    aboutTitle: "혁신적인 난청 관리 기술 | 엠바고 미디어",
    aboutSub: "스마트 주얼리 - 난청 조기진단과 치료의 새로운 기준",
    aboutDescription: "엠바고 미디어는 AI, IoT, 의료 데이터를 결합하여 난청 관리 시장을 혁신합니다. 맞춤형 보청기, AI 기반 챗봇, 청능 재활 솔루션을 만나보세요.",
    aboutSection1Title: "AI 기반 맞춤형 조기 진단 및 재활 상담 서비스",
    aboutSection1Desc: "sLLM을 활용한 맞춤형 난청 관리 솔루션을 통해 데이터 기반 청력 진단 및 최적화된 재활 프로그램을 제공합니다.",
    aboutFeature1: "AI 기반 개인 맞춤형 난청 진단 및 개발",
    aboutFeature1Desc: "sLLM 활용 청력상태 분석 및 맞춤형 재활 제공",
    aboutFeature2: "디지털 자가 진단 시스템",
    aboutFeature2Desc: "병원 방문 없이 청각 관리 가능",
    aboutFeature3: "증폭기 연계 및 보청기 악세서리 개발",
    aboutFeature3Desc: "보청기 주얼리 · IoT연계 기능성과 심미성 동시 강화",
    aboutFeature4: "사운드 테라피 + 그림일기 기반 재활 프로그램",
    aboutFeature4Desc: "인지 재활과 심리 안정 통합 케어",
    aboutStatsTitle: "전세계 15억명, 대한민국은 850만명 이상이 청각장애로 인한 불편함을 가지고 있습니다.",
    aboutStatsDesc: "기존 보청기 시장은 가격, 접근성, 편의성의 문제로 착용률이 현저히 낮습니다. 엠바고 미디어는 이러한 문제를 해결하여 난청 환자의 삶의 질을 높입니다.",
    aboutStep1: "난청 진단 후 보청기 추천",
    aboutStep2: "환자 데이터 활용 맞춤 케어",
    aboutStep3: "솔루션 제공 및 피드백 분석",
    aboutStep4: "환자 삶의 질 향상 및 심리 해결",
    contactTitle: "Contact",
    contactSub: "문의를 남겨주시면 영업일 기준 1~2일내로 연락드리겠습니다.",
    contactName: "이름",
    contactPhone: "연락처",
    contactEmail: "이메일",
    contactMessage: "문의 내용",
    contactAgreement: "개인정보 수집 및 이용 동의",
    contactSubmit: "제출하기",
    contactSuccess: "문의가 성공적으로 접수되었습니다. 곧 연락드리겠습니다.",
    contactAgreeCheckbox: "개인정보 수집 및 이용에 동의합니다.",
    preparingTitle: "서비스 준비 중입니다.",
    preparingSub: "더 나은 서비스를 위해 준비하고 있습니다. 잠시만 기다려 주세요.",
    backToHome: "홈으로 돌아가기",
    saveAsPdf: "PDF로 저장",
    print: "인쇄하기",
    close: "닫기",
  },
  ja: {
    welcome: "こんにちは！Obigeスマート聴覚エージェントへようこそ！👋",
    intro: "AIを使ってあなたの聴覚の健康を分析します。すでに多くの方が私たちのサービスを利用して聴覚を管理しています。😊",
    choose: "以下から選択してください...",
    startTest: "聴力検査開始",
    hearingAid: "補聴器情報",
    others: "その他のお問い合わせ",
    askAge: "まず、年齢を教えてください。",
    askGender: "性別は何ですか？",
    male: "男性",
    female: "女性",
    askNoise: "騒音に頻繁にさらされる環境ですか？",
    askTinnitus: "耳鳴りがありますか？",
    askExisting: "既存の聴覚の問題はありますか？",
    yes: "はい",
    no: "いいえ",
    ptaIntro: "素晴らしい！それでは純音聴力検査を開始します。静かな場所でイヤホンを着用してください。🎧",
    ptaStart: "準備ができました、開始する",
    ptaTesting: "{freq} Hz テスト中...",
    ptaHeard: "聞こえます",
    ptaNotHeard: "聞こえません",
    calculating: "AIが結果を分析しています... 🧠",
    resultsTitle: "聴力検査結果レポート",
    riskScore: "リスクスコア",
    grade: "聴力グレード",
    recommendation: "AI推奨事項",
    retest: "再テスト",
    share: "結果を共有",
    langSwitch: "言語",
    appName: "OBLIGE",
    logout: "ログアウト",
    navWelfare: "福祉金を探す",
    navHearing: "聴力検査",
    navGame: "聴力ゲーム",
    navCommunity: "聴覚の健康",
    findMyWelfareBtn: "私の隠れた福祉金を探す",
    welfarePolicy: "福祉政策の推奨",
    insuranceRecommend: "保険の推奨",
    financeRecommend: "金融商品の推奨",
    askAgeGroup: "年齢層を選択してください。",
    youth: "青少年 (0~19)",
    adult: "青年 (20~60)",
    senior: "高齢者 (61~100)",
    startQuestionnaire: "アンケート開始",
    questionnaireTitle: "聴覚自己診断アンケート",
    next: "次へ",
    skipQuestionnaire: "スキップして聴力検査を開始",
    startQuestionnaireBtn: "アンケート開始",
    landingTitle: "あなたの聴覚年齢は何歳ですか？",
    landingSub: "無料の聴力検査をご利用ください！",
    landingBtn: "検査を開始する",
    nameLabel: "名前",
    namePlaceholder: "名前を入力してください",
    ageLabel: "年齢",
    agePlaceholder: "年齢を入力してください",
    phoneLabel: "電話番号",
    emailLabel: "メールアドレス",
    nextStep: "次のステップへ",
    checkVolume: "音量確認 (1000Hz)",
    communityTitle: "聴覚の健康知識",
    communitySub: "専門家が教える耳の健康管理のヒントと最新情報",
    backToList: "リストに戻る",
    like: "いいね",
    shareBtn: "共有",
    comment: "コメント",
    commentPlaceholder: "意見を残してください...",
    register: "登録",
    firstComment: "最初のコメントを残してください！",
    frequency: "周波数",
    progress: "進行状況",
    aiReport: "AI聴力スクリーニングレポート",
    hearingAgeScreening: "聴力年齢スクリーニング",
    hearingAgeResult: "あなたの聴力は{age}歳レベルです",
    keshhTitle: "韓国型聴覚障害評価指数 (KESHH)",
    keshhScore: "KESHH スコア",
    keshhCategory: "KESHH カテゴリ",
    veryHigh: "非常に高い",
    points: "点",
    category: "カテゴリ",
    cautionTitle: "注意事項",
    cautionText: "本検査は聴力スクリーニング目的で提供されており、医学的診断に代わるものではありません。詳細な聴力検査と正確な診断については、必ず医師にご相談ください。",
    shareWithFriends: "友達と結果を共有する",
    always: "いつも",
    sometimes: "時々",
    preparingTitle: "サービス準備中です",
    preparingSub: "より良いサービスのために準備しています。少々お待ちください。",
    backToHome: "ホームに戻る",
    saveAsPdf: "PDFで保存",
    print: "印刷",
    close: "閉じる",
  },
  zh: {
    welcome: "您好！欢迎使用 Obige 智能听力助手！👋",
    intro: "我将通过 AI 帮助您评估听力健康。我们已经帮助成千上万的人更好地了解他们的听力。😊",
    choose: "请从下方选择...",
    startTest: "开始听力测试",
    hearingAid: "助听器信息",
    others: "其他咨询",
    askAge: "首先，请问您的年龄是多少？",
    askGender: "您的性别是？",
    male: "男",
    female: "女",
    askNoise: "您是否经常暴露在噪音环境中？",
    askTinnitus: "您是否有耳鸣现象？",
    askExisting: "是否有现有的听力问题？",
    yes: "是",
    no: "否",
    ptaIntro: "太棒了！现在我们将开始纯音听力测试。请在安静的地方佩戴耳机。🎧",
    ptaStart: "准备好了，开始测试",
    ptaTesting: "正在测试 {freq} Hz...",
    ptaHeard: "听到了",
    ptaNotHeard: "没听到",
    calculating: "AI 正在分析您的结果... 🧠",
    resultsTitle: "您的听力测试报告",
    riskScore: "风险评分",
    grade: "听力等级",
    recommendation: "AI 建议",
    retest: "重新测试",
    share: "分享结果",
    langSwitch: "语言",
    appName: "OBLIGE",
    logout: "登出",
    navWelfare: "寻找福利金",
    navHearing: "听力测试",
    navGame: "听力游戏",
    navCommunity: "听力健康",
    findMyWelfareBtn: "寻找我隐藏的福利金",
    welfarePolicy: "福利政策推荐",
    insuranceRecommend: "保险推荐",
    financeRecommend: "金融产品推荐",
    askAgeGroup: "请选择您的年龄组。",
    youth: "青少年 (0~19)",
    adult: "成年 (20~60)",
    senior: "老年 (61~100)",
    startQuestionnaire: "开始问卷",
    questionnaireTitle: "听力自我评估问卷",
    next: "下一步",
    skipQuestionnaire: "跳过并开始听力测试",
    startQuestionnaireBtn: "开始问卷",
    landingTitle: "您的听力年龄是多少岁？",
    landingSub: "使用我们的免费听力测试！",
    landingBtn: "开始测试",
    nameLabel: "姓名",
    namePlaceholder: "请输入姓名",
    ageLabel: "年龄",
    agePlaceholder: "请输入年龄",
    phoneLabel: "电话号码",
    emailLabel: "电子邮箱",
    nextStep: "下一步",
    checkVolume: "检查音量 (1000Hz)",
    communityTitle: "听力健康知识",
    communitySub: "专家提供的耳部健康管理技巧和最新信息",
    backToList: "返回列表",
    like: "点赞",
    shareBtn: "分享",
    comment: "评论",
    commentPlaceholder: "留下您的想法...",
    register: "注册",
    firstComment: "留下第一条评论吧！",
    frequency: "频率",
    progress: "进度",
    aiReport: "AI听力筛查报告",
    hearingAgeScreening: "听力年龄筛查",
    hearingAgeResult: "您的听力处于{age}岁水平",
    keshhTitle: "韩国型听力障碍评估指数 (KESHH)",
    keshhScore: "KESHH 评分",
    keshhCategory: "KESHH 类别",
    veryHigh: "非常高",
    points: "分",
    category: "类别",
    cautionTitle: "注意事项",
    cautionText: "本测试仅用于听力筛查，不能代替医学诊断。如需详细的听力检查和准确诊断，请务必咨询医生。",
    shareWithFriends: "与朋友分享结果",
    always: "总是",
    sometimes: "有时",
    preparingTitle: "服务准备中",
    preparingSub: "我们正在准备更好的服务。请稍候。",
    backToHome: "返回首页",
    saveAsPdf: "保存为 PDF",
    print: "打印",
    close: "关闭",
  },
  es: {
    welcome: "¡Hola! ¡Bienvenido al Agente de Audición Inteligente Obige! 👋",
    intro: "Estoy aquí para ayudarte a evaluar tu salud auditiva usando IA. Hemos ayudado a miles de personas a entender mejor su audición. 😊",
    choose: "Elige una opción abajo...",
    startTest: "Prueba de Audición",
    hearingAid: "Información sobre Audífonos",
    others: "Otras Consultas",
    askAge: "Primero, ¿cuál es tu edad?",
    askGender: "¿Cuál es tu género?",
    male: "Masculino",
    female: "Femenino",
    askNoise: "¿Estás expuesto a ruidos frecuentes?",
    askTinnitus: "¿Experimentas tinnitus (zumbido en los oídos)?",
    askExisting: "¿Tienes algún problema auditivo existente?",
    yes: "Sí",
    no: "No",
    ptaIntro: "¡Genial! Ahora comenzaremos la prueba de tono puro. Por favor, usa auriculares en un lugar tranquilo. 🎧",
    ptaStart: "Estoy listo, empezar prueba",
    ptaTesting: "Probando {freq} Hz...",
    ptaHeard: "Lo escuché",
    ptaNotHeard: "Sin sonido",
    calculating: "Analizando tus resultados con IA... 🧠",
    resultsTitle: "Tus Resultados de la Prueba de Audición",
    riskScore: "Puntuación de Riesgo",
    grade: "Grado",
    recommendation: "Recomendación de IA",
    retest: "Repetir prueba",
    share: "Compartir resultados",
    langSwitch: "Idioma",
    appName: "OBLIGE",
    logout: "Cerrar sesión",
    navWelfare: "Buscar Fondos de Bienestar",
    navHearing: "Prueba de Audición",
    navGame: "Juego de Audición",
    navCommunity: "Salud Auditiva",
    findMyWelfareBtn: "Encontrar mis fondos de bienestar ocultos",
    welfarePolicy: "Recomendaciones de Políticas de Bienestar",
    insuranceRecommend: "Recomendaciones de Seguros",
    financeRecommend: "Recomendaciones de Productos Financieros",
    askAgeGroup: "Por favor, selecciona tu grupo de edad.",
    youth: "Joven (0~19)",
    adult: "Adulto (20~60)",
    senior: "Adulto Mayor (61~100)",
    startQuestionnaire: "Comenzar Cuestionario",
    questionnaireTitle: "Autoevaluación Auditiva",
    next: "Siguiente",
    skipQuestionnaire: "Omitir y empezar prueba de audición",
    startQuestionnaireBtn: "Comenzar Cuestionario",
    landingTitle: "¿Qué edad tiene tu audición?",
    landingSub: "¡Usa nuestra prueba de audición gratuita!",
    landingBtn: "Empezar Prueba",
    nameLabel: "Nombre",
    namePlaceholder: "Introduce tu nombre",
    ageLabel: "Edad",
    agePlaceholder: "Introduce tu edad",
    phoneLabel: "Número de teléfono",
    emailLabel: "Correo electrónico",
    nextStep: "Siguiente paso",
    checkVolume: "Comprobar volumen (1000Hz)",
    communityTitle: "Conocimientos sobre salud auditiva",
    communitySub: "Consejos de expertos y última información sobre salud auditiva",
    backToList: "Volver a la lista",
    like: "Me gusta",
    shareBtn: "Compartir",
    comment: "Comentario",
    commentPlaceholder: "Deja tus pensamientos...",
    register: "Registrar",
    firstComment: "¡Sé el primero en comentar!",
    frequency: "Frecuencia",
    progress: "Progreso",
    aiReport: "Informe de detección auditiva por IA",
    hearingAgeScreening: "Detección de edad auditiva",
    hearingAgeResult: "Tu audición está al nivel de {age} años",
    keshhTitle: "Evaluación Coreana de la Discapacidad Auditiva Subjetiva (KESHH)",
    keshhScore: "Puntuación KESHH",
    keshhCategory: "Categoría KESHH",
    veryHigh: "Muy Alto",
    points: "Puntos",
    category: "Categoría",
    cautionTitle: "PRECAUCIÓN",
    cautionText: "Esta prueba es para fines de detección y no es un diagnóstico médico. Consulta a un médico para un examen auditivo detallado y un diagnóstico preciso.",
    shareWithFriends: "Compartir resultados con amigos",
    always: "Siempre",
    sometimes: "A veces",
    preparingTitle: "Servicio en preparación",
    preparingSub: "Estamos preparando un mejor servicio. Por favor, espere un momento.",
    backToHome: "Volver al inicio",
    saveAsPdf: "Guardar como PDF",
    print: "Imprimir",
    close: "Cerrar",
  },
  fr: {
    welcome: "Bonjour ! Bienvenue sur l'Agent Auditif Intelligent Obige ! 👋",
    intro: "Je suis ici pour vous aider à évaluer votre santé auditive grâce à l'IA. Nous avons aidé des milliers de personnes à mieux comprendre leur audition. 😊",
    choose: "Choisissez ci-dessous...",
    startTest: "Test d'Audition",
    hearingAid: "Infos Appareils Auditifs",
    others: "Autres Demandes",
    askAge: "Tout d'abord, quel est votre âge ?",
    askGender: "Quel est votre genre ?",
    male: "Homme",
    female: "Femme",
    askNoise: "Êtes-vous exposé à des bruits fréquents ?",
    askTinnitus: "Souffrez-vous d'acouphènes (bourdonnements d'oreilles) ?",
    askExisting: "Avez-vous des problèmes d'audition existants ?",
    yes: "Oui",
    no: "Non",
    ptaIntro: "Génial ! Nous allons maintenant commencer le test de tonalité pure. Veuillez porter un casque dans un endroit calme. 🎧",
    ptaStart: "Je suis prêt, commencer le test",
    ptaTesting: "Test de {freq} Hz...",
    ptaHeard: "J'ai entendu",
    ptaNotHeard: "Pas de son",
    calculating: "Analyse de vos résultats par l'IA... 🧠",
    resultsTitle: "Vos Résultats du Test d'Audition",
    riskScore: "Score de Risque",
    grade: "Grade",
    recommendation: "Recommandation de l'IA",
    retest: "Refaire le test",
    share: "Partager les résultats",
    langSwitch: "Langue",
    appName: "OBLIGE",
    logout: "Déconnexion",
    navWelfare: "Trouver des Fonds de Bien-être",
    navHearing: "Test d'Audition",
    navGame: "Jeu d'Audition",
    navCommunity: "Santé Auditive",
    findMyWelfareBtn: "Trouver mes fonds de bien-être cachés",
    welfarePolicy: "Recomendations de Politiques de Bien-être",
    insuranceRecommend: "Recommandations d'Assurance",
    financeRecommend: "Recommandations de Produits Financiers",
    askAgeGroup: "Veuillez sélectionner votre groupe d'âge.",
    youth: "Jeune (0~19)",
    adult: "Adulte (20~60)",
    senior: "Senior (61~100)",
    startQuestionnaire: "Commencer le Questionnaire",
    questionnaireTitle: "Auto-évaluation Auditive",
    next: "Suivant",
    skipQuestionnaire: "Passer et commencer le test d'audition",
    startQuestionnaireBtn: "Commencer le Questionnaire",
    landingTitle: "Quel âge a votre audition ?",
    landingSub: "Utilisez notre test d'audition gratuit !",
    landingBtn: "Commencer le Test",
    nameLabel: "Nom",
    namePlaceholder: "Entrez votre nom",
    ageLabel: "Âge",
    agePlaceholder: "Entrez votre âge",
    phoneLabel: "Numéro de téléphone",
    emailLabel: "Adresse e-mail",
    nextStep: "Étape suivante",
    checkVolume: "Vérifier le volume (1000Hz)",
    communityTitle: "Connaissances sur la santé auditive",
    communitySub: "Conseils d'experts et dernières infos sur la santé des oreilles",
    backToList: "Retour à la liste",
    like: "J'aime",
    shareBtn: "Partager",
    comment: "Commentaire",
    commentPlaceholder: "Laissez vos pensées...",
    register: "S'inscrire",
    firstComment: "Soyez le premier à commenter !",
    frequency: "Fréquence",
    progress: "Progression",
    aiReport: "Rapport de dépistage auditif par l'IA",
    hearingAgeScreening: "Dépistage de l'âge auditif",
    hearingAgeResult: "Votre audition est au niveau de {age} ans",
    keshhTitle: "Évaluation Coréenne du Handicap Auditif Subjectif (KESHH)",
    keshhScore: "Score KESHH",
    keshhCategory: "Catégorie KESHH",
    veryHigh: "Très Élevé",
    points: "Points",
    category: "Catégorie",
    cautionTitle: "ATTENTION",
    cautionText: "Ce test est destiné au dépistage et ne constitue pas un diagnostic médical. Veuillez consulter un médecin pour un examen auditif détaillé et un diagnostic précis.",
    shareWithFriends: "Partager les résultats avec des amis",
    always: "Toujours",
    sometimes: "Parfois",
    preparingTitle: "Service en préparation",
    preparingSub: "Nous préparons un meilleur service. Veuillez patienter un instant.",
    backToHome: "Retour à l'accueil",
    saveAsPdf: "Enregistrer en PDF",
    print: "Imprimer",
    close: "Fermer",
  }
};

export const questionnaireQuestions = {
  ko: {
    youth: [
      "평소에 TV나 유튜브 볼륨을 크게 키우나요?",
      "선생님이나 친구의 말을 자주 되묻나요?",
      "귀가 꽉 찬 느낌이나 통증이 자주 있나요?"
    ],
    adult: [
      "시끄러운 식당이나 카페에서 대화가 어렵나요?",
      "전화 통화 시 상대방의 목소리가 작게 들리나요?",
      "귀에서 '삐-' 하는 이명 소리가 들린 적이 있나요?"
    ],
    senior: [
      "난청 때문에 전화걸기(통화하기)가 불편하십니까?",
      "난청 때문에 낯선 사람을 만나거나 집에 누가 오면 싫으십니까?",
      "친척, 친구 혹은 이웃과 만나는 것을 회피하십니까?",
      "사회적모임(동창회, 계모임, 교회, 성당, 사찰 등)에 참여하는 것이 어렵습니까?",
      "난청 때문에 본인의 성격이 부정적으로 변했습니까?",
      "병원이나 관공서를 방문했을 때 상담내용을 알아듣기가 어렵습니까?",
      "모임이나 잔치(결혼식, 회갑연, 돌 등)에서 여러 사람들과 대화하기가 어렵습니까?",
      "난청 때문에 짜증이 나거나 바보같이 느껴집니까?",
      "다른 사람이 작은 목소리로 속삭이거나 대화할 때 듣기가 어렵습니까?",
      "TV를 보거나 라디오를 들을 때 내용을 이해하기가 어렵습니까?",
      "식당에서 대화할 때 어렵습니까?",
      "대형장소(강당, 교회, 성당, 사찰 등)에서 강의, 설교, 강론, 설법 등을 들을 때 내용을 알아듣기가 어렵습니까?",
      "대형장소(강당, 교회, 성당, 사찰 등)에서 일대일로 대화할 때 듣기가 어렵습니까?",
      "여러 사람과 대화할 때 엉뚱한 말로 실수를 할까봐 말하기가 두렵습니까?",
      "난청 때문에 다른 사람의 도움이 필요하지는 않다고 느끼십니까?",
      "다른 사람 말을 잘 알아듣지 못하기 때문에 본인말만 하십니까?",
      "난청이 있어도 자신 있고 당당하게 생활하십니까?",
      "본인이 난청이 있음을 남에게 알리기 싫습니까?",
      "난청 때문에 가족이 화를 내거나 다툰 적이 있습니까?",
      "가족, 친지, 주변 사람들과 대화할 때 긴장되십니까?",
      "TV를 보거나 라디오를 들을 때 너무 크게 들어서 주변 사람들과 다툰 적이 있습니까?",
      "가족과 친지들이 당신에게 말할 때 잘 듣지 못해서 힘들어합니까?",
      "가족과 친지들이 당신의 난청에 대하여 잘 이해 해줍니까?",
      "보청기를 착용한 후 주변소리(물 내리는 소리, 열쇠꾸러미소리, 식기 부딪히는 소리 등)가 커서 불편하십니까?",
      "보청기를 착용하면 더 늙어 보인다고 느끼십니까?",
      "보청기를 착용한 모습을 다른 사람이 볼까봐 두렵습니까?",
      "난청 때문에 보청기착용이 필요하십니까?",
      "보청기 착용에 대해서 다른 사람들이 말을 하면 기분이 나쁩니까?",
      "보청기를 착용하면 다른 사람들이 당신을 바보 취급합니까?",
      "보청기 착용이 불만족스럽습니까?"
    ]
  },
  en: {
    youth: [
      "Do you usually turn up the volume on TV or YouTube very loud?",
      "Do you often ask teachers or friends to repeat what they said?",
      "Do you often feel your ears are full or have pain?"
    ],
    adult: [
      "Is it difficult to have a conversation in a noisy restaurant or cafe?",
      "Does the other person's voice sound small during phone calls?",
      "Have you ever heard a 'beep' sound (tinnitus) in your ears?"
    ],
    senior: [
      "Is it uncomfortable to make phone calls because of hearing loss?",
      "Do you dislike meeting strangers or visitors because of hearing loss?",
      "Do you avoid meeting relatives, friends, or neighbors?",
      "Is it difficult to participate in social gatherings (alumni meetings, church, etc.)?",
      "Has your personality changed negatively because of hearing loss?",
      "Is it difficult to understand consultations when visiting hospitals or public offices?",
      "Is it difficult to talk with many people at gatherings or parties?",
      "Do you feel annoyed or foolish because of hearing loss?",
      "Is it difficult to hear when others whisper or talk in a low voice?",
      "Is it difficult to understand TV or radio content?",
      "Is it difficult to talk in a restaurant?",
      "Is it difficult to understand lectures or sermons in large venues?",
      "Is it difficult to have a one-on-one conversation in large venues?",
      "Are you afraid of making mistakes when talking with many people?",
      "Do you feel that you don't need help from others despite hearing loss?",
      "Do you only talk yourself because you can't understand others?",
      "Do you live confidently even with hearing loss?",
      "Do you dislike letting others know you have hearing loss?",
      "Has your family ever been angry or argued because of your hearing loss?",
      "Do you feel tense when talking with family, relatives, or neighbors?",
      "Have you ever argued with family because the TV/radio volume was too loud?",
      "Do family and relatives find it hard to talk to you because you can't hear well?",
      "Do family and relatives understand your hearing loss well?",
      "Are ambient sounds (water, keys, dishes) too loud after wearing hearing aids?",
      "Do you feel you look older when wearing hearing aids?",
      "Are you afraid others will see you wearing hearing aids?",
      "Do you need hearing aids because of hearing loss?",
      "Do you feel bad when others talk about your hearing aid use?",
      "Do others treat you like a fool when you wear hearing aids?",
      "Are you dissatisfied with wearing hearing aids?"
    ]
  },
  ja: {
    youth: [
      "普段、テレビやYouTubeの音量を大きくしますか？",
      "先生や友達の言葉をよく聞き返しますか？",
      "耳が詰まった感じや痛みが頻繁にありますか？"
    ],
    adult: [
      "騒がしいレストランやカフェで会話が難しいですか？",
      "電話中に相手の声が小さく聞こえますか？",
      "耳の中で「ピー」という音（耳鳴り）が聞こえたことがありますか？"
    ],
    senior: [
      "難聴のために電話をかけるのが不便ですか？",
      "難聴のために見知らぬ人に会ったり、誰かが家に来たりするのが嫌ですか？",
      "親戚、友人、近所の人に会うのを避けますか？",
      "社会的な集まり（同窓会、教会など）に参加するのが難しいですか？",
      "難聴のために自分の性格が否定的に変わりましたか？",
      "病院や役所を訪れた際、相談内容を聞き取るのが難しいですか？",
      "集まりやパーティーで多くの人と会話するのが難しいですか？",
      "難聴のためにイライラしたり、自分が馬鹿のように感じたりしますか？",
      "他の人が小さな声で囁いたり会話したりする際、聞き取りにくいですか？",
      "テレビやラジオの内容を理解するのが難しいですか？",
      "レストランでの会話が難しいですか？",
      "広い場所（講堂、教会など）で講義や説教を聞き取るのが難しいですか？",
      "広い場所で一対一の会話をする際、聞き取りにくいですか？",
      "多くの人と会話する際、とんちんかんなことを言って失敗するのではないかと不安ですか？",
      "難聴があっても、他人の助けは必要ないと感じますか？",
      "他人の話がよく聞き取れないため、自分の話ばかりしますか？",
      "難聴があっても自信を持って堂々と生活していますか？",
      "自分が難聴であることを他人に知られたくないですか？",
      "難聴のために家族が怒ったり喧嘩したりしたことがありますか？",
      "家族や親戚、周囲の人と会話する際に緊張しますか？",
      "テレビやラジオの音が大きすぎて周囲の人と喧嘩したことがありますか？",
      "家族や親戚が、あなたの聞き取りが悪いために苦労していますか？",
      "家族や親戚は、あなたの難聴についてよく理解してくれますか？",
      "補聴器を着用した後、周囲の音（水の流れる音、鍵の音、食器の音など）が大きくて不快ですか？",
      "補聴器を着用すると、より老けて見えると感じますか？",
      "補聴器を着用している姿を他人に見られるのが怖いですか？",
      "難聴のために補聴器の着用が必要ですか？",
      "補聴器の着用について他人が何か言うと、嫌な気分になりますか？",
      "補聴器を着用すると、他人があなたを馬鹿扱いしますか？",
      "補聴器の着用に不満がありますか？"
    ]
  },
  zh: {
    youth: [
      "平时看电视或 YouTube 时会把音量开得很大吗？",
      "经常需要老师或朋友重复他们说的话吗？",
      "经常感到耳朵胀满或疼痛吗？"
    ],
    adult: [
      "在嘈杂的餐厅或咖啡馆里交谈困难吗？",
      "通话时对方的声音听起来很小吗？",
      "耳朵里是否听过“哔——”的耳鸣声？"
    ],
    senior: [
      "因为听力下降，打电话感到不便吗？",
      "因为听力下降，讨厌见陌生人或有人来家里吗？",
      "是否回避与亲戚、朋友或邻居见面？",
      "参加社会聚会（同学会、教会等）是否困难？",
      "因为听力下降，您的性格是否变得消极了？",
      "去医院或政府部门时，是否难以听清咨询内容？",
      "在聚会或宴会上，是否难以与多人交谈？",
      "因为听力下降，是否感到烦躁或觉得自已很笨？",
      "别人小声说话或私语时，是否难以听清？",
      "看电视或听收音机时，是否难以理解内容？",
      "在餐厅交谈是否困难？",
      "在大型场所（礼堂、教会等）听讲座或讲道时，是否难以听清内容？",
      "在大型场所进行一对一交谈时，是否难以听清？",
      "与多人交谈时，是否担心说错话而不敢开口？",
      "是否觉得即使听力下降也不需要别人的帮助？",
      "因为听不清别人的话，所以只顾自已说话吗？",
      "即使有听力问题，也能自信大方地生活吗？",
      "是否不想让别人知道自已听力不好？",
      "因为听力问题，家人是否曾生气或发生争吵？",
      "与家人、亲戚 or 周围人交谈时会感到紧张吗？",
      "看电视或听收音机音量太大，是否曾与周围人发生争吵？",
      "家人和亲戚是否因为您听不清而感到辛苦？",
      "家人和亲戚是否理解您的听力问题？",
      "佩戴助听器后，周围的声音（流水声、钥匙声、餐具碰撞声等）是否太大而感到不适？",
      "是否觉得佩戴助听器看起来更老？",
      "是否担心别人看到您佩戴助听器的样子？",
      "因为听力下降，您需要佩戴助听器吗？",
      "当别人谈论您佩戴助听器时，会感到不快吗？",
      "佩戴助听器时，别人会把您当成傻瓜吗？",
      "对佩戴助听器感到不满意吗？"
    ]
  },
  es: {
    youth: [
      "¿Sueles subir mucho el volumen de la televisión o de YouTube?",
      "¿A menudo pides a profesores o amigos que repitan lo que dijeron?",
      "¿Sientes a menudo los oídos tapados o tienes dolor?"
    ],
    adult: [
      "¿Es difícil mantener una conversación en un restaurante o café ruidoso?",
      "¿La voz de la otra persona suena baja durante las llamadas telefónicas?",
      "¿Alguna vez has escuchado un pitido (tinnitus) en tus oídos?"
    ],
    senior: [
      "¿Le resulta incómodo hacer llamadas telefónicas debido a la pérdida de audición?",
      "¿Le disgusta conocer gente nueva o recibir visitas debido a la pérdida de audición?",
      "¿Evita encontrarse con familiares, amigos o vecinos?",
      "¿Le resulta difícil participar en reuniones sociales (reuniones de ex alumnos, iglesia, etc.)?",
      "¿Ha cambiado su personalidad negativamente debido a la pérdida de audición?",
      "¿Le resulta difícil entender las consultas cuando visita hospitales u oficinas públicas?",
      "¿Le resulta difícil hablar con varias personas en reuniones o fiestas?",
      "¿Se siente molesto o tonto debido a la pérdida de audición?",
      "¿Le resulta difícil oír cuando otros susurran o hablan en voz baja?",
      "¿Le resulta difícil entender el contenido de la televisión o la radio?",
      "¿Le resulta difícil hablar en un restaurante?",
      "¿Le resulta difícil entender conferencias o sermones en lugares grandes?",
      "¿Le resulta difícil tener una conversación individual en lugares grandes?",
      "¿Tiene miedo de cometer errores al hablar con muchas personas?",
      "¿Siente que no necesita ayuda de otros a pesar de la pérdida de audición?",
      "¿Solo habla usted mismo porque no puede entender a los demás?",
      "¿Vive con confianza incluso con pérdida de audición?",
      "¿Le disgusta que otros sepan que tiene pérdida de audición?",
      "¿Su familia se ha enojado o ha discutido alguna vez debido a su pérdida de audición?",
      "¿Se siente tenso al hablar con familiares, parientes o vecinos?",
      "¿Alguna vez ha discutido con la familia porque el volumen de la TV/radio era demasiado alto?",
      "¿A sus familiares y parientes les resulta difícil hablar con usted porque no oye bien?",
      "¿Sus familiares y parientes entienden bien su pérdida de audición?",
      "¿Los sonidos ambientales (agua, llaves, platos) son demasiado fuertes después de usar audífonos?",
      "¿Siente que se ve más viejo cuando usa audífonos?",
      "¿Tiene miedo de que otros lo vean usando audífonos?",
      "¿Necesita audífonos debido a la pérdida de audición?",
      "¿Se siente mal cuando otros hablan sobre su uso de audífonos?",
      "¿Otros lo tratan como un tonto cuando usa audífonos?",
      "¿Está insatisfecho con el uso de audífonos?"
    ]
  },
  fr: {
    youth: [
      "Augmentez-vous souvent le volume de la télévision ou de YouTube très fort ?",
      "Demandez-vous souvent aux professeurs ou aux amis de répéter ce qu'ils ont dit ?",
      "Ressentez-vous souvent une sensation d'oreille bouchée ou une douleur ?"
    ],
    adult: [
      "Est-il difficile d'avoir une conversation dans un restaurant ou un café bruyant ?",
      "La voix de l'autre personne semble-t-elle faible lors des appels téléphoniques ?",
      "Avez-vous déjà entendu un sifflement (acouphène) dans vos oreilles ?"
    ],
    senior: [
      "Est-il inconfortable de passer des appels téléphoniques à cause de la perte auditive ?",
      "N'aimez-vous pas rencontrer des inconnus ou recevoir des visiteurs à cause de la perte auditive ?",
      "Évitez-vous de rencontrer des parents, des amis ou des voisins ?",
      "Est-il difficile de participer à des réunions sociales (réunions d'anciens élèves, église, etc.) ?",
      "Votre personnalité a-t-elle changé négativement à cause de la perte auditive ?",
      "Est-il difficile de comprendre les consultations lors de visites à l'hôpital ou dans des bureaux publics ?",
      "Est-il difficile de parler avec plusieurs personnes lors de réunions ou de fêtes ?",
      "Vous sentez-vous agacé ou stupide à cause de la perte auditive ?",
      "Est-il difficile d'entendre quand les autres chuchotent ou parlent à voix basse ?",
      "Est-il difficile de comprendre le contenu de la télévision ou de la radio ?",
      "Est-il difficile de parler dans un restaurant ?",
      "Est-il difficile de comprendre des conférences ou des sermons dans de grands lieux ?",
      "Est-il difficile d'avoir une conversation en tête-à-tête dans de grands lieux ?",
      "Avez-vous peur de faire des erreurs en parlant avec plusieurs personnes ?",
      "Pensez-vous que vous n'avez pas besoin de l'aide des autres malgré la perte auditive ?",
      "Parlez-vous seul parce que vous ne pouvez pas comprendre les autres ?",
      "Vivez-vous avec confiance même avec une perte auditive ?",
      "N'aimez-vous pas que les autres sachent que vous avez une perte auditive ?",
      "Votre famille s'est-elle déjà mise en colère ou s'est-elle disputée à cause de votre perte auditive ?",
      "Vous sentez-vous tendu en parlant avec votre famille, vos proches ou vos voisins ?",
      "Vous êtes-vous déjà disputé avec votre famille parce que le volume de la TV/radio était trop élevé ?",
      "Votre famille et vos proches ont-ils du mal à vous parler parce que vous n'entendez pas bien ?",
      "Votre famille et vos proches comprennent-ils bien votre perte auditive ?",
      "Les sons ambiants (eau, clés, vaisselle) sont-ils trop forts après avoir porté des appareils auditifs ?",
      "Avez-vous l'impression de paraître plus vieux lorsque vous portez des appareils auditifs ?",
      "Avez-vous peur que les autres vous voient porter des appareils auditifs ?",
      "Avez-vous besoin d'appareils auditifs à cause de la perte auditive ?",
      "Vous sentez-vous mal quand les autres parlent de votre utilisation d'appareils auditifs ?",
      "Les autres vous traitent-ils comme un idiot quand vous portez des appareils auditifs ?",
      "Êtes-vous mécontent de porter des appareils auditifs ?"
    ]
  }
};
